/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htc.toolkit;

/**
 *
 * @author marco
 */
public class HTCToolkitGUI extends javax.swing.JFrame {

    /**
     * Creates new form HTCToolkitGUI
     */
    public HTCToolkitGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPlatformSelector = new javax.swing.ButtonGroup();
        panelMenubar = new javax.swing.JPanel();
        labelAppTitle = new javax.swing.JLabel();
        radioButtonMac = new javax.swing.JRadioButton();
        radioButtonWindows = new javax.swing.JRadioButton();
        radioButtonLinux = new javax.swing.JRadioButton();
        tabbedPanelMain = new javax.swing.JTabbedPane();
        panelSetupPage = new javax.swing.JPanel();
        panelSetup = new javax.swing.JPanel();
        panelGainRoot = new javax.swing.JPanel();
        labelGainRoot = new javax.swing.JLabel();
        buttonFlashSuperSU = new javax.swing.JButton();
        labelThanksDonate = new javax.swing.JLabel();
        panelUnlockBootloader = new javax.swing.JPanel();
        labelUnlockBootloader = new javax.swing.JLabel();
        getSuperCID = new javax.swing.JButton();
        buttonUnlockBootloader = new javax.swing.JButton();
        buttonGetTokenID = new javax.swing.JButton();
        panelFlashRecovery = new javax.swing.JPanel();
        labelFlashRecovery = new javax.swing.JLabel();
        buttonFlashTWRP = new javax.swing.JButton();
        panelCommandsPage = new javax.swing.JPanel();
        panelCommands = new javax.swing.JPanel();
        panelReboot = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        buttonReboot = new javax.swing.JButton();
        buttonRebootBootloader = new javax.swing.JButton();
        buttonRebootRecovery = new javax.swing.JButton();
        panelFlash = new javax.swing.JPanel();
        labelFlash = new javax.swing.JLabel();
        buttonFlashKernel = new javax.swing.JButton();
        buttonFlashRecovery = new javax.swing.JButton();
        buttonSideloadFile = new javax.swing.JButton();
        panelOther = new javax.swing.JPanel();
        labelOther = new javax.swing.JLabel();
        buttonPushFile = new javax.swing.JButton();
        buttonInstallApp = new javax.swing.JButton();
        buttonRelockBootloader = new javax.swing.JButton();
        panelAboutPage = new javax.swing.JPanel();
        panelAbout = new javax.swing.JPanel();
        panelInformation = new javax.swing.JPanel();
        labelInformation = new javax.swing.JLabel();
        buttonHelp = new javax.swing.JButton();
        buttonRequest = new javax.swing.JButton();
        buttonDevices = new javax.swing.JButton();
        panelDownloads = new javax.swing.JPanel();
        labelDownloads = new javax.swing.JLabel();
        buttonDownloadToolkit = new javax.swing.JButton();
        buttonDownloadRecoveries = new javax.swing.JButton();
        buttonDownloadSource = new javax.swing.JButton();
        panelContact = new javax.swing.JPanel();
        labelContact = new javax.swing.JLabel();
        buttonXDAPM = new javax.swing.JButton();
        buttonEmailMe = new javax.swing.JButton();
        buttonTwitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaDroid Toolkit ");

        panelMenubar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelAppTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelAppTitle.setText("JavaDroid Toolkit");

        buttonGroupPlatformSelector.add(radioButtonMac);
        radioButtonMac.setText("Mac");
        radioButtonMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonMacActionPerformed(evt);
            }
        });

        buttonGroupPlatformSelector.add(radioButtonWindows);
        radioButtonWindows.setText("Windows");

        buttonGroupPlatformSelector.add(radioButtonLinux);
        radioButtonLinux.setText("Linux");

        javax.swing.GroupLayout panelMenubarLayout = new javax.swing.GroupLayout(panelMenubar);
        panelMenubar.setLayout(panelMenubarLayout);
        panelMenubarLayout.setHorizontalGroup(
            panelMenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAppTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButtonMac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonWindows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonLinux)
                .addContainerGap())
        );
        panelMenubarLayout.setVerticalGroup(
            panelMenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAppTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButtonMac)
                    .addComponent(radioButtonWindows)
                    .addComponent(radioButtonLinux))
                .addContainerGap())
        );

        panelGainRoot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelGainRoot.setText("3. Gain Root");

        buttonFlashSuperSU.setText("Flash SuperSU");

        labelThanksDonate.setText("<html>Thanks for using the JavaDroid Toolkit! Please consider donating!</html>");

        javax.swing.GroupLayout panelGainRootLayout = new javax.swing.GroupLayout(panelGainRoot);
        panelGainRoot.setLayout(panelGainRootLayout);
        panelGainRootLayout.setHorizontalGroup(
            panelGainRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGainRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGainRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGainRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGainRootLayout.createSequentialGroup()
                        .addGroup(panelGainRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelThanksDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(buttonFlashSuperSU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        panelGainRootLayout.setVerticalGroup(
            panelGainRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGainRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGainRoot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonFlashSuperSU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelThanksDonate)
                .addContainerGap())
        );

        panelUnlockBootloader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelUnlockBootloader.setText("1. Unlock Bootloader");

        getSuperCID.setText("Get SuperCID");
        getSuperCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSuperCIDActionPerformed(evt);
            }
        });

        buttonUnlockBootloader.setText("Unlock Bootloader");

        buttonGetTokenID.setText("Get Token ID");

        javax.swing.GroupLayout panelUnlockBootloaderLayout = new javax.swing.GroupLayout(panelUnlockBootloader);
        panelUnlockBootloader.setLayout(panelUnlockBootloaderLayout);
        panelUnlockBootloaderLayout.setHorizontalGroup(
            panelUnlockBootloaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnlockBootloaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUnlockBootloaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getSuperCID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelUnlockBootloader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonUnlockBootloader, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(buttonGetTokenID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelUnlockBootloaderLayout.setVerticalGroup(
            panelUnlockBootloaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnlockBootloaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUnlockBootloader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getSuperCID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGetTokenID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonUnlockBootloader)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelFlashRecovery.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelFlashRecovery.setText("2. Flash Recovery");

        buttonFlashTWRP.setText("Flash TWRP");

        javax.swing.GroupLayout panelFlashRecoveryLayout = new javax.swing.GroupLayout(panelFlashRecovery);
        panelFlashRecovery.setLayout(panelFlashRecoveryLayout);
        panelFlashRecoveryLayout.setHorizontalGroup(
            panelFlashRecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFlashRecoveryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFlashRecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFlashRecovery, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(buttonFlashTWRP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFlashRecoveryLayout.setVerticalGroup(
            panelFlashRecoveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFlashRecoveryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFlashRecovery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonFlashTWRP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSetupLayout = new javax.swing.GroupLayout(panelSetup);
        panelSetup.setLayout(panelSetupLayout);
        panelSetupLayout.setHorizontalGroup(
            panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUnlockBootloader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFlashRecovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelGainRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelSetupLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {panelGainRoot, panelUnlockBootloader});

        panelSetupLayout.setVerticalGroup(
            panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelGainRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFlashRecovery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUnlockBootloader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSetupPageLayout = new javax.swing.GroupLayout(panelSetupPage);
        panelSetupPage.setLayout(panelSetupPageLayout);
        panelSetupPageLayout.setHorizontalGroup(
            panelSetupPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSetup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSetupPageLayout.setVerticalGroup(
            panelSetupPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupPageLayout.createSequentialGroup()
                .addComponent(panelSetup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabbedPanelMain.addTab("Setup", panelSetupPage);

        panelReboot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Reboot");

        buttonReboot.setText("Reboot");

        buttonRebootBootloader.setText("Bootloader");

        buttonRebootRecovery.setText("Recovery");

        javax.swing.GroupLayout panelRebootLayout = new javax.swing.GroupLayout(panelReboot);
        panelReboot.setLayout(panelRebootLayout);
        panelRebootLayout.setHorizontalGroup(
            panelRebootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRebootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRebootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonReboot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(buttonRebootBootloader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRebootRecovery, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRebootLayout.setVerticalGroup(
            panelRebootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRebootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonReboot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRebootRecovery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRebootBootloader)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelFlash.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelFlash.setText("Flash");

        buttonFlashKernel.setText("Flash Kernel");

        buttonFlashRecovery.setText("Flash Recovery");

        buttonSideloadFile.setText("Sideload File");

        javax.swing.GroupLayout panelFlashLayout = new javax.swing.GroupLayout(panelFlash);
        panelFlash.setLayout(panelFlashLayout);
        panelFlashLayout.setHorizontalGroup(
            panelFlashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFlashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFlashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFlash, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(buttonFlashKernel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFlashRecovery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSideloadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFlashLayout.setVerticalGroup(
            panelFlashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFlashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFlash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonFlashKernel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFlashRecovery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSideloadFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOther.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelOther.setText("Other");

        buttonPushFile.setText("Push File");

        buttonInstallApp.setText("Install App");
        buttonInstallApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInstallAppActionPerformed(evt);
            }
        });

        buttonRelockBootloader.setText("Relock Bootloader");

        javax.swing.GroupLayout panelOtherLayout = new javax.swing.GroupLayout(panelOther);
        panelOther.setLayout(panelOtherLayout);
        panelOtherLayout.setHorizontalGroup(
            panelOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOther, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(buttonPushFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonInstallApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRelockBootloader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelOtherLayout.setVerticalGroup(
            panelOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOther)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPushFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInstallApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRelockBootloader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCommandsLayout = new javax.swing.GroupLayout(panelCommands);
        panelCommands.setLayout(panelCommandsLayout);
        panelCommandsLayout.setHorizontalGroup(
            panelCommandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCommandsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelReboot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFlash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCommandsLayout.setVerticalGroup(
            panelCommandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCommandsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCommandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelReboot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFlash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOther, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCommandsPageLayout = new javax.swing.GroupLayout(panelCommandsPage);
        panelCommandsPage.setLayout(panelCommandsPageLayout);
        panelCommandsPageLayout.setHorizontalGroup(
            panelCommandsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
            .addGroup(panelCommandsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCommandsPageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCommands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelCommandsPageLayout.setVerticalGroup(
            panelCommandsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
            .addGroup(panelCommandsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCommandsPageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCommands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabbedPanelMain.addTab("Commands", panelCommandsPage);

        panelInformation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelInformation.setText("Information");

        buttonHelp.setText("Help");

        buttonRequest.setText("Request");

        buttonDevices.setText("Devices");

        javax.swing.GroupLayout panelInformationLayout = new javax.swing.GroupLayout(panelInformation);
        panelInformation.setLayout(panelInformationLayout);
        panelInformationLayout.setHorizontalGroup(
            panelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(buttonRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDevices, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInformationLayout.setVerticalGroup(
            panelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDevices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRequest)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelDownloads.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelDownloads.setText("Downloads");

        buttonDownloadToolkit.setText("Toolkit");

        buttonDownloadRecoveries.setText("Recoveries");

        buttonDownloadSource.setText("Source Code");

        javax.swing.GroupLayout panelDownloadsLayout = new javax.swing.GroupLayout(panelDownloads);
        panelDownloads.setLayout(panelDownloadsLayout);
        panelDownloadsLayout.setHorizontalGroup(
            panelDownloadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownloadsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDownloadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDownloads, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(buttonDownloadToolkit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDownloadRecoveries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDownloadSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDownloadsLayout.setVerticalGroup(
            panelDownloadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownloadsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDownloads)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonDownloadToolkit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDownloadRecoveries)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDownloadSource)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelContact.setText("Contact");

        buttonXDAPM.setText("XDA PM");

        buttonEmailMe.setText("E-Mail");

        buttonTwitter.setText("Twitter");

        javax.swing.GroupLayout panelContactLayout = new javax.swing.GroupLayout(panelContact);
        panelContact.setLayout(panelContactLayout);
        panelContactLayout.setHorizontalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContact, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(buttonXDAPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEmailMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTwitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelContactLayout.setVerticalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonXDAPM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEmailMe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTwitter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDownloads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDownloads, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAboutPageLayout = new javax.swing.GroupLayout(panelAboutPage);
        panelAboutPage.setLayout(panelAboutPageLayout);
        panelAboutPageLayout.setHorizontalGroup(
            panelAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
            .addGroup(panelAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAboutPageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelAboutPageLayout.setVerticalGroup(
            panelAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
            .addGroup(panelAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAboutPageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabbedPanelMain.addTab("About", panelAboutPage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabbedPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelMenubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonMacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonMacActionPerformed

    private void getSuperCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSuperCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getSuperCIDActionPerformed

    private void buttonInstallAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInstallAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInstallAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HTCToolkitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HTCToolkitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HTCToolkitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HTCToolkitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HTCToolkitGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDevices;
    private javax.swing.JButton buttonDownloadRecoveries;
    private javax.swing.JButton buttonDownloadSource;
    private javax.swing.JButton buttonDownloadToolkit;
    private javax.swing.JButton buttonEmailMe;
    private javax.swing.JButton buttonFlashKernel;
    private javax.swing.JButton buttonFlashRecovery;
    private javax.swing.JButton buttonFlashSuperSU;
    private javax.swing.JButton buttonFlashTWRP;
    private javax.swing.JButton buttonGetTokenID;
    private javax.swing.ButtonGroup buttonGroupPlatformSelector;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonInstallApp;
    private javax.swing.JButton buttonPushFile;
    private javax.swing.JButton buttonReboot;
    private javax.swing.JButton buttonRebootBootloader;
    private javax.swing.JButton buttonRebootRecovery;
    private javax.swing.JButton buttonRelockBootloader;
    private javax.swing.JButton buttonRequest;
    private javax.swing.JButton buttonSideloadFile;
    private javax.swing.JButton buttonTwitter;
    private javax.swing.JButton buttonUnlockBootloader;
    private javax.swing.JButton buttonXDAPM;
    private javax.swing.JButton getSuperCID;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelAppTitle;
    private javax.swing.JLabel labelContact;
    private javax.swing.JLabel labelDownloads;
    private javax.swing.JLabel labelFlash;
    private javax.swing.JLabel labelFlashRecovery;
    private javax.swing.JLabel labelGainRoot;
    private javax.swing.JLabel labelInformation;
    private javax.swing.JLabel labelOther;
    private javax.swing.JLabel labelThanksDonate;
    private javax.swing.JLabel labelUnlockBootloader;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JPanel panelAboutPage;
    private javax.swing.JPanel panelCommands;
    private javax.swing.JPanel panelCommandsPage;
    private javax.swing.JPanel panelContact;
    private javax.swing.JPanel panelDownloads;
    private javax.swing.JPanel panelFlash;
    private javax.swing.JPanel panelFlashRecovery;
    private javax.swing.JPanel panelGainRoot;
    private javax.swing.JPanel panelInformation;
    private javax.swing.JPanel panelMenubar;
    private javax.swing.JPanel panelOther;
    private javax.swing.JPanel panelReboot;
    private javax.swing.JPanel panelSetup;
    private javax.swing.JPanel panelSetupPage;
    private javax.swing.JPanel panelUnlockBootloader;
    private javax.swing.JRadioButton radioButtonLinux;
    private javax.swing.JRadioButton radioButtonMac;
    private javax.swing.JRadioButton radioButtonWindows;
    private javax.swing.JTabbedPane tabbedPanelMain;
    // End of variables declaration//GEN-END:variables
}
